ExplainingAvatar:
 preparation: True # your can set it to False if you want to use the existing avator, it will save time
 bbox_shift: 5
 video_path: "data/video/IdleVideo.mp4"
 audio_clips:
     introVideo: "data/audio/audio/intro.mp3"


     